name: i386 linux tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/cache@v3
          with:
            path: |
              ~/.cache/go-build
              ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ${{ runner.os }}-go-
        - name: Build
          run: make geth
        - name: Archive
          uses: actions/upload-artifact@v4
          with:
            name: bin
            path: |
              build/bin
              sendEth.js
  stress-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: bin
      - name: Listing files
        run: ls -R
      - name: Install Web3.js
        run: npm install web3
      - name: Start Geth in Development Mode
        run: |
          chmod +x build/bin/geth
          nohup ./build/bin/geth --dev --http --http.api "personal,eth,net,web3" --http.addr "0.0.0.0" --http.port 8545 &
          sleep 5 # Wait for geth to start
      - name: Send ETH
        run: node sendEth.js
      - name: Install pandoras-box
        run: npm install -g pandoras-box
      - name: Run stress test
        run: pandoras-box -url http://127.0.0.1:8545 -m "erupt oven loud noise rug proof sunset gas table era dizzy vault" -t 1 -b 5 -o ./myOutput.json
      # - name: Set up Go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: 1.21.4
      # - name: Run tests
      #   run: go test -short ./...
      #   env:
      #     GOOS: linux
      #     GOARCH: 386
