name: i386 linux tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/cache@v3
          with:
            path: |
              ~/.cache/go-build
              ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ${{ runner.os }}-go-
        - name: Build
          run: make all
        - name: Archive
          uses: actions/upload-artifact@v4
          with:
            name: bin
            path: |
              build/bin
              sendEth.js
  spec-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: bin
      - name: Listing files
        run: |
          ls -R
          pwd
      - name: Install related tools
        run: |
          sudo add-apt-repository -y ppa:ethereum/ethereum
          sudo apt-get update
          sudo apt-get install ethereum solc
      - name: Clone execution-spec-tests
        run: |
          git clone https://github.com/ethereum/execution-spec-tests
          cd execution-spec-tests
          python3 -m venv ./venv/
          source ./venv/bin/activate
          pip install -e '.[docs,lint,test]'
      - name: Print working directory
        run: pwd
      - name: List all files
        run: ls build/bin
      - name: Test spec
        run: |
          chmod +x ./build/bin/evm
          cd execution-spec-tests
          source ./venv/bin/activate
          solc-select install 0.8.26
          solc-select use 0.8.26
          fill --fork=Cancun --evm-bin=../build/bin/evm -v tests/berlin/eip2930_access_list/test_acl.py

